### ISSUE TITLE
Uncaught TypeError: chart.select is not a function

### ISSUE THREAD

**Issue by chogarcia** [tj/d3-series#3]
I took the example and tried to run it. 

I got: `Uncaught TypeError: chart.select is not a function` on [this line](https://github.com/tj/d3-series/blob/master/index.js#L241)

Any help?

**Comment by tj** [comment]
Hmm sounds like you're maybe doing `foo = LineChart()` instead of `foo = new LineChart()` or something, somehow `this.chart =` is not getting assigned from the constructor

**Comment by chogarcia** [comment]
I am doing same as the example:
```
    this.b = new Chart({
      target: this.refs.b,
      ease: 'elastic',
      height: 250
    })
```

Is there any example on codepen, jsfiddle or similar I can take a look at?

**Comment by tj** [comment]
Nah I don't use those sorry, there's only https://github.com/tj/d3-series/tree/master/example
